app/Http/routes.php
<?php

use App\Models\SaleSummary;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('phpinfo', function () {
	return view('phpinfo');
});
Route::get('/test', function(){
	
	$files = File::allFiles(storage_path().'/uploads/sftp');

	foreach ($files as $file)
	{	
		$info = pathinfo($file);
		$type = 1;
		$filename = $info['filename'];
		if(substr($filename,0,9) == "INVENTORY" ){
			$type = 2;
			$branch_code = substr($filename,12,4);
			$transact_date = substr($filename,17,4)."-".substr($filename,21,2)."-".substr($filename,23,2);
		}else{
			$branch_code = substr($filename,8,4);
			$transact_date = substr($filename,13,4)."-".substr($filename,17,2)."-".substr($filename,19,2);
		}
		// dd($transact_date);

	 	App/Models/SalesInventory::firstOrCreate(['type' => $type, 
	 		'branch_code' => $branch_code, 
	 		'file' => $filename,
	 		'transact_date' => $transact_date]);

	}
});

Route::get('/webhooks', function(){
	
	$channelSecret = "c466dce5c4a6d05ce9cb34ef7d49edbf"; // Channel secret string
	$httpRequestBody = " "; // Request body string
	$hash = hash_hmac('sha256', $httpRequestBody, $channelSecret, true);
	$signature = base64_encode($hash);
	echo $signature;
	
});


Route::get('/daily',function(Request $request){

	// $datas = SaleSummary::getDailyandMonthlySales($request);
	// // dd($datas);die;
	// \Mail::send('email.daily_sales',$data = [
	// 	'datas' => $datas], function ($message) use($data){
 //        $message->from('admin@chasetech.com', 'Daily Sales Report');
 //        $message->to("jpoxcz@gmail.com")->subject('Sales Report');
 //        });

	dd(date('G'));

});

// Route::auth();

Route::group(array('prefix' => 'api'), function(){
	Route::post('uploadpo', 'Api\PurchaseOrderController@uploadpo');
	Route::post('upselltype', 'Api\SalesSummaryController@branchtype');
	Route::post('incomingbranch', 'Api\IncomingItemController@stocksstorebranch');
	Route::post('incomingcategory', 'Api\IncomingItemController@stocksstorecategory');
	Route::post('incomingbrand', 'Api\IncomingItemController@stocksstorebrand');
	Route::post('uploadincoming', 'Api\IncomingItemController@uploadincoming'); 

	Route::post('outgoingbranch', 'Api\OutgoingItemController@stocksstorebranch');
	Route::post('outgoingcategory', 'Api\OutgoingItemController@stocksstorecategory');
	Route::post('outgoingbrand', 'Api\OutgoingItemController@stocksstorebrand');
	Route::post('uploadoutgoing', 'Api\OutgoingItemController@uploadoutgoing'); 

	Route::post('uploadsales', 'Api\SalesSummaryController@uploadsales');
	Route::post('storebranch', 'Api\SalesSummaryController@storebranch');
	Route::post('branchterminal', 'Api\SalesSummaryController@branchterminal');
	Route::post('globalstatus', 'Api\SalesSummaryController@globalstatus');
	
	Route::post('uploadrefund', 'Api\RefundItemController@uploadrefund'); 
	Route::post('uploadreturn', 'Api\ReturnExchangeController@uploadreturn'); 

	Route::post('uploadpostvoid', 'Api\PostVoidContoller@uploadpostvoid'); 

	Route::get('checkgiftcard/{code?}', 'Api\GiftCardController@checkgiftcard'); 
	Route::post('uploadgiftcard', 'Api\GiftCardController@uploadgiftcard'); 

	Route::post('uploadinventory', 'Api\ItemStockController@uploadinventory');
	Route::post('stocksstorebranch', 'Api\ItemStockController@stocksstorebranch');

	Route::post('coupon', 'Api\CouponController@store'); 
	Route::get('coupon/{code?}', 'Api\CouponController@verify'); 

	Route::get('downloadmasterfile', 'Api\ItemMasterfileController@downloadmasterfile');

	Route::get('outgoing/{company_code}/{branch_code}', 'Api\OutgoingItemController@outgoing');

	Route::post('sftp', 'Api\SftpController@sftp'); 
	Route::post('salesinventory', 'Api\SalesInventoryController@store'); 

	Route::post('sftp_excel', 'Api\SftpController@excel_upload');
	Route::post('get_companies','Api\SftpController@get_companies');
	Route::post('masterfile', 'Api\MasterfileController@upload'); 
	Route::get('masterfile', 'Api\MasterfileController@download');

	Route::get('download_voucher','Api\ManualInventoryController@download');

	
	Route::post('uploadpatient', 'Api\PatientController@uploadpatient'); 

	Route::post('outgoingitem', 'Api\OutgoingItemController@getitem'); 

	Route::post('salesfromtokyo','Api\CrossSiteController@uploadsalestokyo');
	Route::post('retexfromtokyo','Api\CrossSiteController@uploadretextokyo');
	Route::post('incomingfromtokyo','Api\CrossSiteController@uploadincomingtokyo');
	//new added
	Route::post('storebrand','Api\SalesSummaryController@storebrand');
	Route::post('outgoinguser', 'Api\OutgoingItemController@stocksuser'); 
	//close new added
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::post('login', 'Auth\AuthController@postLogin');

Route::group(['middleware' => ['auth']], function () {
	Route::group(['middleware' => ['role:admin']], function(){
		Route::resource('items', 'FileMaintenance\ItemController');
		Route::resource('companies', 'FileMaintenance\CompanyController');
		Route::resource('branches', 'FileMaintenance\BranchController');
		Route::resource('branchesettings', 'FileMaintenance\BranchSettingController');
		Route::resource('roles', 'FileMaintenance\RoleController');
		Route::resource('giftcards', 'FileMaintenance\GiftCardController');
		Route::resource('brand' ,'FileMaintenance\BrandController');
		Route::resource('duplicate','FileMaintenance\DuplicateItemController');
		Route::resource('changeitem','FileMaintenance\ChangeItemController');
		Route::get('users/{id}/branch', ['as' => 'users.branch', 'uses' => 'FileMaintenance\UserController@branch']);
		Route::post('users/{id}/branch', ['as' => 'users.storebranch', 'uses' => 'FileMaintenance\UserController@storebranch']);
		
		Route::resource('zap', 'FileMaintenance\ZapController');
		Route::resource('zap_per_day', 'FileMaintenance\ZapPerDayController');
		Route::get('branch_item/{id}',['as'=>'branch.item','uses'=>'FileMaintenance\ItemController@branch_item']);
	});
	Route::resource('users', 'FileMaintenance\UserController');
		Route::get('users/changepassword',['as'=>'users.changepassword','uses'=>'FileMaintenance\UserController@show']);
		Route::post('users/update/{password}',['as'=>'users.updatepassword','uses'=>'FileMaintenance\UserController@updatepassword']);
	Route::get('/', 'HomeController@index');
	Route::resource('outgoing', 'InventoryReport\OutgoingReportController');
	Route::resource('incoming', 'InventoryReport\IncomingReportController');
	Route::resource('purchase', 'InventoryReport\PurchaseOrderController');

	Route::get('stocks/{id}/history', ['as' => 'stocks.history', 'uses' => 'InventoryReport\ItemStockController@history']);
	Route::resource('stocks', 'InventoryReport\ItemStockController');

	Route::get('sales/{id}/items', ['as' => 'sales.items', 'uses' => 'SalesReport\SalesSummaryController@items']);
	Route::get('sales/{id}/transaction', ['as' => 'sales.transaction', 'uses' => 'SalesReport\SalesSummaryController@transaction']);
	Route::post('items_sales_summary_report',['as' => 'sales.items.report','uses' => 'SalesReport\SalesSummaryController@download_items_sales']);
	Route::resource('sales', 'SalesReport\SalesSummaryController');
	Route::resource('salemans', 'SalesReport\SalesManController');
	Route::resource('refunds', 'SalesReport\RefundReportController');
	Route::resource('returnexchange', 'SalesReport\ReturnExchnageReportController');
	Route::resource('postvoid', 'SalesReport\PostVoidController');
	Route::resource('coupons', 'SalesReport\CouponController');
	Route::resource('itemrank', 'SalesReport\ItemRankController');
	Route::resource('upsell', 'SalesReport\UpsellController');

	Route::resource('salesinventory', 'Utility\SalesInventoryExportController');
	Route::resource('inventorysummary', 'Utility\SalesInventorySummaryExportController');
	Route::get('salessummary',['as' => 'salessummary.index', 'uses' => 'Utility\SalesInventorySummaryExportController@show']);
	Route::post('salessummary/generate',['as' => 'salessummary.generate', 'uses' => 'Utility\SalesInventorySummaryExportController@generate']);
	// Route::get('salesinventorysummary',['as'=>'salesinventorysummary.index','uses'=>'Utility\SalesInventoryExportController@sindex']);
	// Route::post('salesinventorysummary/generate',['as'=>'salesinventorysummary.sgenerate','uses'=>'Utility\SalesInventoryExportController@sgenerate']);
	Route::resource('manualinventory', 'Utility\ManualInventoryController');
	Route::resource('patient', 'Utility\PatientHistoryController');
	Route::get('other_payment',['as' => 'other.payment' , 'uses' => 'FileMaintenance\GiftCardController@other_payment']);

	Route::get('check_excel',['as' =>'check.excel','uses' => 'Utility\CheckUploadController@excel_index']);
	Route::post('check_excel',['as' => 'excel.post' , 'uses' => 'Utility\CheckUploadController@excel_post']);

	Route::get('check_csv',['as' =>'check.csv','uses' => 'Utility\CheckUploadController@csv_index']);

	//inventory stock excel report

	// Route::get('stock_transfer_in',['as' => 'stock_transfer_in.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_index']);

	// Route::post('stock_transfer_in',['as' => 'stock_transfer_in.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_store']);

	// Route::get('stock_transfer_out',['as' => 'stock_transfer_out.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_index']);

	// Route::post('stock_transfer_out',['as' => 'stock_transfer_out.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_store']);

resources/views/stocks/history.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush
@push('inline-scripts')
    @if(isset($sel_branches))
    var branches = <?php echo json_encode($sel_branches); ?>;
    @else
    var branches = [];
    @endif

    @if(isset($sel_categories))
    var categories = <?php echo json_encode($sel_categories); ?>;
    @else
    var categories = [];
    @endif

    @if(isset($sel_brands))
    var brands = <?php echo json_encode($sel_brands); ?>;
    @else
    var brands = [];
    @endif
@endpush
@push('scripts')
    <script src="{{ asset("js/stock.js") }}"></script>
@endpush
@section('main_container')

    <!-- page content -->
    <div class="right_col" role="main">
         <div class="">
            <div class="page-title">
                <div class="title_left">
                    <a href="{{ route('stocks.index')}}" class="btn btn-default">Back</a>
                </div>
                 
            </div>

            <div class="x_panel">
                 
                  <div class="x_content">
                    <br>
                    <div class="form-horizontal form-label-left">

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Company Name </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" disabled="disabled" value="{{ $branch->company->company }}" placeholder="Disabled Input">
                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Branch Name </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" disabled="disabled" value="{{ $branch->branch}}" placeholder="Disabled Input">
                            </div>
                      </div>




                       <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Branch Code </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" disabled="disabled" value="{{ $branch->branch_code}}" placeholder="Disabled Input">
                        </div>
                      </div>

                     
                      </div>

                    </div>
                  </div>
                </div>

                 <div class="clearfix"></div>

            {!! Form::open(array('route' => array('stocks.history',$branch->branch_code), 'class' => 'form-horizontal form-label-left', 'method' => 'GET')) !!}
                   <input type="hidden" name="branch" class="form-control" disabled="disabled" value="{{ $branch->branch_code }}" placeholder="Disabled Input">
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="row">

                                 <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="company">Category Name</label>
                                        {!! Form::select('category[]',$sel_categories, null, array('id' => 'category', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT A CATEGORY...')) !!}
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="company">Brand Name</label>
                                        {!! Form::select('brand[]',$sel_brands, null, array('id' => 'brand', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT A BRAND...')) !!}
                                    </div>
                                </div>       
                                



                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="stock_status">Stock Status</label>
                                        {!! Form::select('status[]',  $stock_status, null, array('id' => 'stock_status', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT DIVISION')) !!}
                                    </div>
                                </div>



                                <div class="col-md-12 col-xs-12">
                                    <div class="form-group">
                                        <label for="keywords">Search</label>
                                        {!! Form::text('keyword',null,array('class' => 'form-control', 'id' => 'keyword','placeholder' =>'Enter Item')) !!}
                                    </div>
                                    
                               
                            </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-success">Process</button>
                                    </div>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
        {!! Form::close() !!}

             <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Items</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div>
                     
                          {!! $items->render() !!}
                        {!! Paginate::show($items) !!} 

                    </div>

                        <div class="x_content table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Barcode</th>
                                        <th>Category</th>
                                        <th>ItemCode</th>
                                        <th>Description</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if(count($items) > 0)
                                    @foreach($items as $item)
                                    <tr>
                                        <td>{{ $item->barcode }}</td>
                                        <td>{{ $item->category }}</td>
                                        <td>{{ $item->itemcode }}</td>
                                        <td>{{ $item->description }}</td>
                                        <td>{{ $item->qty }}</td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan="3">No record found</td>
                                    </tr>
                                    @endif
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
     <div class="clearfix"></div>
      <!--       <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Item Movement Report</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Beginning Inventory</th>
                                        <th>Ending Inventory</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if(count($histories) > 0)
                                    @foreach($histories as $history)
                                    <tr>
                                        <td>{{ $history->transaction_date }}</td>
                                        <td>{{ $history->begining }}</td>
                                        <td>{{ $history->ending }}</td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan="3">No record found</td>
                                    </tr>
                                    @endif
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div> -->
          </div>
    </div>
    <!-- /page content -->

@endsection

resources/views/stocks/index.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@push('inline-scripts')
    @if(isset($sel_branches))
    var branches = <?php echo json_encode($sel_branches); ?>;
    @else
    var branches = [];
    @endif
@endpush

@push('scripts')
    <script src="{{ asset("js/itemstocks.js") }}"></script>
@endpush

@section('main_container')

    <!-- page content -->
    <div class="right_col" role="main">
         <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Branch Item Stock Report</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            {!! Form::open(array('route' => array('stocks.store'), 'class' => 'form-horizontal form-label-left', 'method' => 'POST')) !!}
                  
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="row">

                                

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="company">Company Name</label>
                                        {!! Form::select('company[]',  $companies, null, array('id' => 'company', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT DIVISION')) !!}
                                    </div>
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="branch">Branch Name</label>
                                        <select class="form-control" data-placeholder="SELECT A BRANCH..." id="branch" name="branch[]" multiple="multiple" ></select>
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="stock_status">Stock Status</label>
                                        {!! Form::select('status[]',  $stock_status, null, array('id' => 'status', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT DIVISION')) !!}
                                    </div>
                                </div>



                                <div class="col-md-12 col-xs-12">
                                    <div class="form-group">
                                        <label for="keywords">Search</label>
                                        {!! Form::text('keyword',null,array('class' => 'form-control', 'id' => 'keyword','placeholder' =>'Enter Item')) !!}
                                    </div>
                                    
                               
                            </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-success">Process</button>
                                    </div>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
        {!! Form::close() !!}


            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                      <div class="x_title">
                            <h2>Item Stoks</h2>
                            <div class="pull-right">
                                <h3>Total Qty: {!! $total_stock !!}</h3>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content table-responsive">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Company Name</th>
                                        <th>Branch Name</th>
                                        <th>Total Stocks</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>


                                <tbody>
                                    @if(count($items) > 0)
                                    @foreach($items as $item)
                                    <tr>
                                        <td>{{ $item->company_name }}</td>
                                        <td>{{ $item->branch_name }}</td>
                                        <td class="right">{{ number_format($item->total_stocks) }}</td>
                                        <td>
                                            <a href="{{ route('stocks.history', $item->branch_code)}}"> Details</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @else
                                    
                                    @endif
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
          </div>
    </div>
    <!-- /page content -->

@endsection

resources/views/stocks/show.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@section('main_container')


@endsection