app/Http/routes.php
			$transact_date = substr($filename,13,4)."-".substr($filename,17,2)."-".substr($filename,19,2);
		}
		// dd($transact_date);

	 	App/Models/SalesInventory::firstOrCreate(['type' => $type, 
	 		'branch_code' => $branch_code, 
	 		'file' => $filename,
	 		'transact_date' => $transact_date]);

	}
});

Route::get('/webhooks', function(){
	
	$channelSecret = "c466dce5c4a6d05ce9cb34ef7d49edbf"; // Channel secret string
	$httpRequestBody = " "; // Request body string
	$hash = hash_hmac('sha256', $httpRequestBody, $channelSecret, true);
	$signature = base64_encode($hash);
	echo $signature;
	
});


Route::get('/daily',function(Request $request){

	// $datas = SaleSummary::getDailyandMonthlySales($request);
	// // dd($datas);die;
	// \Mail::send('email.daily_sales',$data = [
	// 	'datas' => $datas], function ($message) use($data){
 //        $message->from('admin@chasetech.com', 'Daily Sales Report');
 //        $message->to("jpoxcz@gmail.com")->subject('Sales Report');
 //        });

	dd(date('G'));

});

// Route::auth();

Route::group(array('prefix' => 'api'), function(){
	Route::post('uploadpo', 'Api\PurchaseOrderController@uploadpo');
	Route::post('upselltype', 'Api\SalesSummaryController@branchtype');
	Route::post('incomingbranch', 'Api\IncomingItemController@stocksstorebranch');
	Route::post('incomingcategory', 'Api\IncomingItemController@stocksstorecategory');
	Route::post('incomingbrand', 'Api\IncomingItemController@stocksstorebrand');
	Route::post('uploadincoming', 'Api\IncomingItemController@uploadincoming'); 

	Route::post('outgoingbranch', 'Api\OutgoingItemController@stocksstorebranch');
	Route::post('outgoingcategory', 'Api\OutgoingItemController@stocksstorecategory');
	Route::post('outgoingbrand', 'Api\OutgoingItemController@stocksstorebrand');
	Route::post('uploadoutgoing', 'Api\OutgoingItemController@uploadoutgoing'); 

	Route::post('uploadsales', 'Api\SalesSummaryController@uploadsales');
	Route::post('storebranch', 'Api\SalesSummaryController@storebranch');
	Route::post('branchterminal', 'Api\SalesSummaryController@branchterminal');
	Route::post('globalstatus', 'Api\SalesSummaryController@globalstatus');
	
	Route::post('uploadrefund', 'Api\RefundItemController@uploadrefund'); 
	Route::post('uploadreturn', 'Api\ReturnExchangeController@uploadreturn'); 

	Route::post('uploadpostvoid', 'Api\PostVoidContoller@uploadpostvoid'); 

	Route::get('checkgiftcard/{code?}', 'Api\GiftCardController@checkgiftcard'); 
	Route::post('uploadgiftcard', 'Api\GiftCardController@uploadgiftcard'); 

	Route::post('uploadinventory', 'Api\ItemStockController@uploadinventory');
	Route::post('stocksstorebranch', 'Api\ItemStockController@stocksstorebranch');

	Route::post('coupon', 'Api\CouponController@store'); 
	Route::get('coupon/{code?}', 'Api\CouponController@verify'); 

	Route::get('downloadmasterfile', 'Api\ItemMasterfileController@downloadmasterfile');

	Route::get('outgoing/{company_code}/{branch_code}', 'Api\OutgoingItemController@outgoing');

	Route::post('sftp', 'Api\SftpController@sftp'); 
	Route::post('salesinventory', 'Api\SalesInventoryController@store'); 

	Route::post('sftp_excel', 'Api\SftpController@excel_upload');
	Route::post('get_companies','Api\SftpController@get_companies');
	Route::post('masterfile', 'Api\MasterfileController@upload'); 
	Route::get('masterfile', 'Api\MasterfileController@download');

	Route::get('download_voucher','Api\ManualInventoryController@download');

	
	Route::post('uploadpatient', 'Api\PatientController@uploadpatient'); 

	Route::post('outgoingitem', 'Api\OutgoingItemController@getitem'); 

	Route::post('salesfromtokyo','Api\CrossSiteController@uploadsalestokyo');
	Route::post('retexfromtokyo','Api\CrossSiteController@uploadretextokyo');
	Route::post('incomingfromtokyo','Api\CrossSiteController@uploadincomingtokyo');
	//new added
	Route::post('storebrand','Api\SalesSummaryController@storebrand');
	Route::post('outgoinguser', 'Api\OutgoingItemController@stocksuser'); 
	//close new added
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::post('login', 'Auth\AuthController@postLogin');

Route::group(['middleware' => ['auth']], function () {
	Route::group(['middleware' => ['role:admin']], function(){
		Route::resource('items', 'FileMaintenance\ItemController');
		Route::resource('companies', 'FileMaintenance\CompanyController');
		Route::resource('branches', 'FileMaintenance\BranchController');
		Route::resource('branchesettings', 'FileMaintenance\BranchSettingController');
		Route::resource('roles', 'FileMaintenance\RoleController');
		Route::resource('giftcards', 'FileMaintenance\GiftCardController');
		Route::resource('brand' ,'FileMaintenance\BrandController');
		Route::resource('duplicate','FileMaintenance\DuplicateItemController');
		Route::resource('changeitem','FileMaintenance\ChangeItemController');
		Route::get('users/{id}/branch', ['as' => 'users.branch', 'uses' => 'FileMaintenance\UserController@branch']);
		Route::post('users/{id}/branch', ['as' => 'users.storebranch', 'uses' => 'FileMaintenance\UserController@storebranch']);
		
		Route::resource('zap', 'FileMaintenance\ZapController');
		Route::resource('zap_per_day', 'FileMaintenance\ZapPerDayController');
		Route::get('branch_item/{id}',['as'=>'branch.item','uses'=>'FileMaintenance\ItemController@branch_item']);
	});
	Route::resource('users', 'FileMaintenance\UserController');
		Route::get('users/changepassword',['as'=>'users.changepassword','uses'=>'FileMaintenance\UserController@show']);
		Route::post('users/update/{password}',['as'=>'users.updatepassword','uses'=>'FileMaintenance\UserController@updatepassword']);
	Route::get('/', 'HomeController@index');
	Route::resource('outgoing', 'InventoryReport\OutgoingReportController');
	Route::resource('incoming', 'InventoryReport\IncomingReportController');
	Route::resource('purchase', 'InventoryReport\PurchaseOrderController');

	Route::get('stocks/{id}/history', ['as' => 'stocks.history', 'uses' => 'InventoryReport\ItemStockController@history']);
	Route::resource('stocks', 'InventoryReport\ItemStockController');

	Route::get('sales/{id}/items', ['as' => 'sales.items', 'uses' => 'SalesReport\SalesSummaryController@items']);
	Route::get('sales/{id}/transaction', ['as' => 'sales.transaction', 'uses' => 'SalesReport\SalesSummaryController@transaction']);
	Route::post('items_sales_summary_report',['as' => 'sales.items.report','uses' => 'SalesReport\SalesSummaryController@download_items_sales']);
	Route::resource('sales', 'SalesReport\SalesSummaryController');
	Route::resource('salemans', 'SalesReport\SalesManController');
	Route::resource('refunds', 'SalesReport\RefundReportController');
	Route::resource('returnexchange', 'SalesReport\ReturnExchnageReportController');
	Route::resource('postvoid', 'SalesReport\PostVoidController');
	Route::resource('coupons', 'SalesReport\CouponController');
	Route::resource('itemrank', 'SalesReport\ItemRankController');
	Route::resource('upsell', 'SalesReport\UpsellController');

	Route::resource('salesinventory', 'Utility\SalesInventoryExportController');
	Route::resource('inventorysummary', 'Utility\SalesInventorySummaryExportController');
	Route::get('salessummary',['as' => 'salessummary.index', 'uses' => 'Utility\SalesInventorySummaryExportController@show']);
	Route::post('salessummary/generate',['as' => 'salessummary.generate', 'uses' => 'Utility\SalesInventorySummaryExportController@generate']);
	// Route::get('salesinventorysummary',['as'=>'salesinventorysummary.index','uses'=>'Utility\SalesInventoryExportController@sindex']);
	// Route::post('salesinventorysummary/generate',['as'=>'salesinventorysummary.sgenerate','uses'=>'Utility\SalesInventoryExportController@sgenerate']);
	Route::resource('manualinventory', 'Utility\ManualInventoryController');
	Route::resource('patient', 'Utility\PatientHistoryController');
	Route::get('other_payment',['as' => 'other.payment' , 'uses' => 'FileMaintenance\GiftCardController@other_payment']);

	Route::get('check_excel',['as' =>'check.excel','uses' => 'Utility\CheckUploadController@excel_index']);
	Route::post('check_excel',['as' => 'excel.post' , 'uses' => 'Utility\CheckUploadController@excel_post']);

	Route::get('check_csv',['as' =>'check.csv','uses' => 'Utility\CheckUploadController@csv_index']);

	//inventory stock excel report

	// Route::get('stock_transfer_in',['as' => 'stock_transfer_in.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_index']);

	// Route::post('stock_transfer_in',['as' => 'stock_transfer_in.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_store']);

	// Route::get('stock_transfer_out',['as' => 'stock_transfer_out.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_index']);

	// Route::post('stock_transfer_out',['as' => 'stock_transfer_out.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_store']);

	// Route::get('stock_movement_detailed',['as' => 'stock_movement_detailed.index','uses'=>'InventoryReport\ExcelReportController@stock_movement_detailed_index']);


	// Route::post('stock_movement_detailed',['as' => 'stock_movement_detailed.store','uses'=>'InventoryReport\ExcelReportController@stock_movement_detailed_store']);



	// Route::get('stock_movement_summary',['as' => 'stock_movement_summary.index','uses'=>'InventoryReport\ExcelReportController@stock_movement_summary_index']);

	// Route::post('stock_movement_summary',['as' => 'stock_movement_summary.store','uses'=>'InventoryReport\ExcelReportController@stock_movement_summary_store']);


	//inventory stock excel report

	Route::get('stock_transfer_in',['as' => 'stock_transfer_in.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_index']);

	Route::post('stock_transfer_in',['as' => 'stock_transfer_in.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_store']);

app/Models/ManualInventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ManualInventory extends Model
{
    protected $fillable = [
        'branch_id', 
        'voucher_number',
        'filename'
    ];

    public static function getFiles(){
    	return self::select('manual_inventories.id', 'manual_inventories.filename','manual_inventories.voucher_number','manual_inventories.created_at',
    		'company_branches.branch_code', 'company_branches.branch')
    		->join('company_branches', 'company_branches.id', '=', 'manual_inventories.branch_id')
    		->get();
    }
}

app/Http/Controllers/Api/ManualInventoryController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ManualInventory;

class ManualInventoryController extends Controller
{
    public function download(Request $request){

    	$voucher = $request->get('voucher_number');

    	$file = ManualInventory::where('voucher_number',$voucher)->first();
    	
    	if(!empty($file)){
    		$pathToFile = storage_path().'/uploads/manualinventory/'.$file->filename;
			return response()->download($pathToFile);
    	}   
    	else{

    		return response()->json(array('msg' => 'voucher number not found!', 'status' => 0));
    	} 	
    }
}

app/Http/Controllers/Utility/ManualInventoryController.php
<?php

namespace App\Http\Controllers\Utility;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\UserBranch;
use App\Models\ManualInventory;
use Auth;
use Session;

class ManualInventoryController extends Controller
{
    public function index(){
    	$files = ManualInventory::getFiles();
    	return view('manualinventory.index', compact('files'));
    }

    public function create(){
    	$branches = UserBranch::getUserBranch2(Auth::user()->id);
    	return view('manualinventory.create', compact('branches'));
    }

    public function store(Request $request){
       
    	if($request->hasFile('files')){
    		$branch_id = $request->branch;
			$files = $request->file('files');
			$destinationPath = storage_path().'/uploads/manualinventory/';

			if (!\File::exists($destinationPath))
	        {
	            mkdir($destinationPath, 0755, true); 
	        }

			foreach ($files as $file) {
				if(!empty($file)){
					$original_file_name = $file->getClientOriginalName();
					$file->move($destinationPath,$original_file_name);
                    $newstr = substr($original_file_name, strlen($original_file_name) - 9);                    

					ManualInventory::create([
                        'branch_id' => $branch_id, 
                        'voucher_number' => substr($newstr,0,5),
                        'filename' => $original_file_name
                    ]);

				}
				
			}
			
		}

		Session::flash('flash_message', 'File successfully uploaded.');
        Session::flash('flash_class', 'alert-success');

        return redirect()->route("manualinventory.index");
    }

    public function show($id){
    	$file = ManualInventory::find($id);
    	$pathToFile = storage_path().'/uploads/manualinventory/'.$file->filename;
    	return response()->download($pathToFile);
    }
}

resources/views/manualinventory/create.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@push('inline-scripts')
    $('#filer_input').filer({
        changeInput: true,
        showThumbs: true,
        addMore: true
    });

    $('#submitBtn').click(function(){

        $('#confirm-submit').modal('show');

    });

    $('#submit').click(function(){

    $('#formField').submit();



    });
@endpush

@section('main_container')




 <!-- page content -->
<div class="right_col" role="main">

    <div class="">
        <div class="page-title">
        </div>

        @include('includes/notifications')

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Manual Inventory</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br>
                        {!! Form::open(array('route' => 'manualinventory.store','class' => 'form-horizontal form-label-left', 'id'=>'formField',  'files'=>true)) !!}

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role">Branch <span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {!! Form::select('branch', $branches, null, array('class' => 'form-control', 'placeholder' => 'Pick a Branch...')) !!}
                                </div>
                            </div>

                             <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role">Attach Files <span class="required">*</span></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="file" name="files" id="filer_input" multiple="multiple">
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <a class="btn btn-primary" href="{{ route('manualinventory.index')}}">Back</a>
                                    <button type="button" class="btn btn-success" data-target="#confirm-submit" id="submitBtn">Submit</button>
                                </div>
                            </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
    @include('modals.confirmation')
@endsection

@push('scripts')
   
@endpush

resources/views/manualinventory/index.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@section('main_container')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
        </div>
          @include('includes/notifications')

        <div class="clearfix"></div>


        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Manual Inventory</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div>
                        <a class="btn btn-success" href="{{ route('manualinventory.create')}}">Upload Inventory List</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Branch Code</th>
                                    <th>Branch Name</th>
                                    <th>Voucher Number</th>
                                    <th>File Name</th>
                                    <th>Date Uploaded</th>
                                    <th class="action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               @if($files->count() > 0)
                                @foreach($files as $file)
                                <tr>
                                    <td>{{ $file->branch_code }}</td>
                                    <td>{{ $file->branch }}</td>
                                    <td>{{ $file->voucher_number }}</td>
                                    <td>{{ $file->filename }}</td>
                                    <td>{{ $file->created_at }}</td>
                                    <td>
                                        <a class="btn btn-info btn-xs" href="{{ route('manualinventory.show', $file->id)}}">Download</a>
                                    </td>
                                    
                                </tr>
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="14">No record found</td>
                                </tr>
                                @endif
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
    
@endsection