app/Http/routes.php
<?php

use App\Models\SaleSummary;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('phpinfo', function () {
	return view('phpinfo');
});
Route::get('/test', function(){
	
	$files = File::allFiles(storage_path().'/uploads/sftp');

	foreach ($files as $file)
	{	
		$info = pathinfo($file);
		$type = 1;
		$filename = $info['filename'];
		if(substr($filename,0,9) == "INVENTORY" ){
			$type = 2;
			$branch_code = substr($filename,12,4);
			$transact_date = substr($filename,17,4)."-".substr($filename,21,2)."-".substr($filename,23,2);
		}else{
			$branch_code = substr($filename,8,4);
			$transact_date = substr($filename,13,4)."-".substr($filename,17,2)."-".substr($filename,19,2);
		}
		// dd($transact_date);

	 	App/Models/SalesInventory::firstOrCreate(['type' => $type, 
	 		'branch_code' => $branch_code, 
	 		'file' => $filename,
	 		'transact_date' => $transact_date]);

	}
});

Route::get('/webhooks', function(){
	
	$channelSecret = "c466dce5c4a6d05ce9cb34ef7d49edbf"; // Channel secret string
	$httpRequestBody = " "; // Request body string
	$hash = hash_hmac('sha256', $httpRequestBody, $channelSecret, true);
	$signature = base64_encode($hash);
	echo $signature;
	
});


Route::get('/daily',function(Request $request){

	// $datas = SaleSummary::getDailyandMonthlySales($request);
	// // dd($datas);die;
	// \Mail::send('email.daily_sales',$data = [
	// 	'datas' => $datas], function ($message) use($data){
 //        $message->from('admin@chasetech.com', 'Daily Sales Report');
 //        $message->to("jpoxcz@gmail.com")->subject('Sales Report');
 //        });

	dd(date('G'));

});

// Route::auth();

Route::group(array('prefix' => 'api'), function(){
	Route::post('uploadpo', 'Api\PurchaseOrderController@uploadpo');
	Route::post('upselltype', 'Api\SalesSummaryController@branchtype');
	Route::post('incomingbranch', 'Api\IncomingItemController@stocksstorebranch');
	Route::post('incomingcategory', 'Api\IncomingItemController@stocksstorecategory');
	Route::post('incomingbrand', 'Api\IncomingItemController@stocksstorebrand');
	Route::post('uploadincoming', 'Api\IncomingItemController@uploadincoming'); 

	Route::post('outgoingbranch', 'Api\OutgoingItemController@stocksstorebranch');
	Route::post('outgoingcategory', 'Api\OutgoingItemController@stocksstorecategory');
	Route::post('outgoingbrand', 'Api\OutgoingItemController@stocksstorebrand');
	Route::post('uploadoutgoing', 'Api\OutgoingItemController@uploadoutgoing'); 

	Route::post('uploadsales', 'Api\SalesSummaryController@uploadsales');
	Route::post('storebranch', 'Api\SalesSummaryController@storebranch');
	Route::post('branchterminal', 'Api\SalesSummaryController@branchterminal');
	Route::post('globalstatus', 'Api\SalesSummaryController@globalstatus');
	
	Route::post('uploadrefund', 'Api\RefundItemController@uploadrefund'); 
	Route::post('uploadreturn', 'Api\ReturnExchangeController@uploadreturn'); 

	Route::post('uploadpostvoid', 'Api\PostVoidContoller@uploadpostvoid'); 

	Route::get('checkgiftcard/{code?}', 'Api\GiftCardController@checkgiftcard'); 
	Route::post('uploadgiftcard', 'Api\GiftCardController@uploadgiftcard'); 

	Route::post('uploadinventory', 'Api\ItemStockController@uploadinventory');
	Route::post('stocksstorebranch', 'Api\ItemStockController@stocksstorebranch');

	Route::post('coupon', 'Api\CouponController@store'); 
	Route::get('coupon/{code?}', 'Api\CouponController@verify'); 

	Route::get('downloadmasterfile', 'Api\ItemMasterfileController@downloadmasterfile');

	Route::get('outgoing/{company_code}/{branch_code}', 'Api\OutgoingItemController@outgoing');

	Route::post('sftp', 'Api\SftpController@sftp'); 
	Route::post('salesinventory', 'Api\SalesInventoryController@store'); 

	Route::post('sftp_excel', 'Api\SftpController@excel_upload');
	Route::post('get_companies','Api\SftpController@get_companies');
	Route::post('masterfile', 'Api\MasterfileController@upload'); 
	Route::get('masterfile', 'Api\MasterfileController@download');

	Route::get('download_voucher','Api\ManualInventoryController@download');

	
	Route::post('uploadpatient', 'Api\PatientController@uploadpatient'); 

	Route::post('outgoingitem', 'Api\OutgoingItemController@getitem'); 

	Route::post('salesfromtokyo','Api\CrossSiteController@uploadsalestokyo');
	Route::post('retexfromtokyo','Api\CrossSiteController@uploadretextokyo');
	Route::post('incomingfromtokyo','Api\CrossSiteController@uploadincomingtokyo');
	//new added
	Route::post('storebrand','Api\SalesSummaryController@storebrand');
	Route::post('outgoinguser', 'Api\OutgoingItemController@stocksuser'); 
	//close new added
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::post('login', 'Auth\AuthController@postLogin');

Route::group(['middleware' => ['auth']], function () {
	Route::group(['middleware' => ['role:admin']], function(){
		Route::resource('items', 'FileMaintenance\ItemController');
		Route::resource('companies', 'FileMaintenance\CompanyController');
		Route::resource('branches', 'FileMaintenance\BranchController');
		Route::resource('branchesettings', 'FileMaintenance\BranchSettingController');
		Route::resource('roles', 'FileMaintenance\RoleController');
		Route::resource('giftcards', 'FileMaintenance\GiftCardController');
		Route::resource('brand' ,'FileMaintenance\BrandController');
		Route::resource('duplicate','FileMaintenance\DuplicateItemController');
		Route::resource('changeitem','FileMaintenance\ChangeItemController');
		Route::get('users/{id}/branch', ['as' => 'users.branch', 'uses' => 'FileMaintenance\UserController@branch']);
		Route::post('users/{id}/branch', ['as' => 'users.storebranch', 'uses' => 'FileMaintenance\UserController@storebranch']);
		
		Route::resource('zap', 'FileMaintenance\ZapController');
		Route::resource('zap_per_day', 'FileMaintenance\ZapPerDayController');
		Route::get('branch_item/{id}',['as'=>'branch.item','uses'=>'FileMaintenance\ItemController@branch_item']);
	});
	Route::resource('users', 'FileMaintenance\UserController');
		Route::get('users/changepassword',['as'=>'users.changepassword','uses'=>'FileMaintenance\UserController@show']);
		Route::post('users/update/{password}',['as'=>'users.updatepassword','uses'=>'FileMaintenance\UserController@updatepassword']);
	Route::get('/', 'HomeController@index');
	Route::resource('outgoing', 'InventoryReport\OutgoingReportController');
	Route::resource('incoming', 'InventoryReport\IncomingReportController');
	Route::resource('purchase', 'InventoryReport\PurchaseOrderController');

	Route::get('stocks/{id}/history', ['as' => 'stocks.history', 'uses' => 'InventoryReport\ItemStockController@history']);
	Route::resource('stocks', 'InventoryReport\ItemStockController');

	Route::get('sales/{id}/items', ['as' => 'sales.items', 'uses' => 'SalesReport\SalesSummaryController@items']);
	Route::get('sales/{id}/transaction', ['as' => 'sales.transaction', 'uses' => 'SalesReport\SalesSummaryController@transaction']);
	Route::post('items_sales_summary_report',['as' => 'sales.items.report','uses' => 'SalesReport\SalesSummaryController@download_items_sales']);
	Route::resource('sales', 'SalesReport\SalesSummaryController');
	Route::resource('salemans', 'SalesReport\SalesManController');
	Route::resource('refunds', 'SalesReport\RefundReportController');
	Route::resource('returnexchange', 'SalesReport\ReturnExchnageReportController');
	Route::resource('postvoid', 'SalesReport\PostVoidController');
	Route::resource('coupons', 'SalesReport\CouponController');
	Route::resource('itemrank', 'SalesReport\ItemRankController');
	Route::resource('upsell', 'SalesReport\UpsellController');

	Route::resource('salesinventory', 'Utility\SalesInventoryExportController');
	Route::resource('inventorysummary', 'Utility\SalesInventorySummaryExportController');
	Route::get('salessummary',['as' => 'salessummary.index', 'uses' => 'Utility\SalesInventorySummaryExportController@show']);
	Route::post('salessummary/generate',['as' => 'salessummary.generate', 'uses' => 'Utility\SalesInventorySummaryExportController@generate']);
	// Route::get('salesinventorysummary',['as'=>'salesinventorysummary.index','uses'=>'Utility\SalesInventoryExportController@sindex']);
	// Route::post('salesinventorysummary/generate',['as'=>'salesinventorysummary.sgenerate','uses'=>'Utility\SalesInventoryExportController@sgenerate']);
	Route::resource('manualinventory', 'Utility\ManualInventoryController');
	Route::resource('patient', 'Utility\PatientHistoryController');
	Route::get('other_payment',['as' => 'other.payment' , 'uses' => 'FileMaintenance\GiftCardController@other_payment']);

	Route::get('check_excel',['as' =>'check.excel','uses' => 'Utility\CheckUploadController@excel_index']);
	Route::post('check_excel',['as' => 'excel.post' , 'uses' => 'Utility\CheckUploadController@excel_post']);

	Route::get('check_csv',['as' =>'check.csv','uses' => 'Utility\CheckUploadController@csv_index']);

	//inventory stock excel report

	// Route::get('stock_transfer_in',['as' => 'stock_transfer_in.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_index']);

	// Route::post('stock_transfer_in',['as' => 'stock_transfer_in.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_in_store']);

	// Route::get('stock_transfer_out',['as' => 'stock_transfer_out.index','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_index']);

	// Route::post('stock_transfer_out',['as' => 'stock_transfer_out.store','uses'=>'InventoryReport\ExcelReportController@stock_transfer_out_store']);

resources/views/sales/details.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@section('main_container')

    <!-- page content -->
    <div class="right_col" role="main">
         <div class="">
            <div class="page-title">
              <div class="title_left">
                <a href="{{ route('sales.show', ['id' => $summary->branch_code, 'from' => strtotime($date_from), 'to' => strtotime($date_to)])}}" class="btn btn-default">Back</a>
              </div>

            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Trasaction Detail Report</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content table-responsive">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Barcode</th>
                                        <th>Itemcode</th>
                                        <th>Description</th>
                                        <th>Cost</th>
                                        <th>SRP</th>
                                        <th>Qty</th>
                                        <th>Gross Amount</th>
                                        <th>Net Amount</th>
                                        <th>Discount</th>
                                    </tr>
                                </thead>


                                <tbody>
                                    @if(count($sale->details) > 0)
                                    @foreach($sale->details as $item)
                                    <tr>
                                        <td>{{ $item->barcode }}</td>
                                        <td>{{ $item->itemcode }}</td>
                                        <td>{{ $item->description }}</td>
                                        <td>{{ $item->cost }}</td>
                                        <td>{{ $item->srp }}</td>
                                        <td>{{ $item->qty }}</td>
                                        <td>{{ $item->gross_amount }}</td>
                                        <td>{{ $item->net_amount }}</td>
                                        <td>{{ $item->discount }}</td>
                                    </tr>
                                    @endforeach
                                    @else
                                    <tr>
                                        <td colspan="13">No record found</td>
                                    </tr>
                                    @endif
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
          </div>
    </div>
    <!-- /page content -->
@endsection

resources/views/sales/index1.blade.php
@extends('layouts.blank')

@push('stylesheets')

@endpush

@push('inline-scripts')
    @if(isset($sel_branches))
    var branches = <?php echo json_encode($sel_branches); ?>;
    @else
    var branches = [];
    @endif
    @if(isset($sel_terminals))
    var terminals = <?php echo json_encode($sel_terminals); ?>;
    @else
    var terminals = [];
    @endif
@endpush

@push('scripts')
    <script src="{{ asset("js/salessummary.js") }}"></script>
@endpush

@section('main_container')



    <!-- page content -->
    <div class="right_col" role="main">
         <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Sales Summary Report</h3>
                </div>
            </div>

            <div class="clearfix"></div>



            {!! Form::open(array('route' => array('sales.store'), 'class' => 'form-horizontal form-label-left', 'method' => 'POST')) !!}
                  
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="company">Company Name</label>
                                        {!! Form::select('company[]',  $companies, null, array('id' => 'company', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT DIVISION')) !!}
                                    </div>
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="branch">Branch Name</label>
                                        <select class="form-control" data-placeholder="SELECT A BRANCH..." id="branch" name="branch[]" multiple="multiple" ></select>
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="terminal">Terminal</label>
                                        <select class="form-control" data-placeholder="SELECT A TERMINAL..." id="terminal" name="terminal[]" multiple="multiple" ></select>
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="user">User</label>
                                        {!! Form::select('user[]',  $users, null, array('id' => 'user', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT USER')) !!}
                                    </div>
                                    
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="member">Sales Man</label>
                                        {!! Form::select('saleman[]',  $saleman, null, array('id' => 'saleman', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT SALES MAN')) !!}
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="member">Member</label>
                                        {!! Form::select('member[]',  $members, null, array('id' => 'member', 'class' => 'form-control' ,'multiple' => 'multiple' ,'data-placeholder' => 'SELECT MEMBER')) !!}
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="date_from">Date From</label>
                                        {!! Form::text('date_from',$date_from,array('class' => 'form-control', 'id' => 'date_from')) !!}
                                    </div>
                                    
                                </div>

                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="date_to">Date To</label>
                                         {!! Form::text('date_to',$date_to,array('class' => 'form-control', 'id' => 'date_to')) !!}
                                    </div>
                                    
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3 col-xs-12">
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-success">Process</button>
                                    </div>  
                                    <!-- <div class="btn-group">
                                        <button type="submit" value="revenue" name="export" class="btn btn-success">Export Excel</button>
                                    </div> -->
                                    <!-- <div class="btn-group">
                                        <button type="button" class="btn btn-default">Export To Excel</button>
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{{ route('sales.index')}}">Sales Revenue Report</a></li>
                                        </ul>
                                    </div> -->
                                </div>


                                
                            </div>



                        </div>
                    </div>
                </div>  
            {!! Form::close() !!}
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="row tile_count">
                                <div class="col-md-3 col-sm-12 col-xs-12 tile_stats_count">
                                    <span class="count_top"><i class="fa fa-line-chart"></i> Total Net Sales</span>
                                    <div class="count">{{ number_format($summary->net_sales,3) }}</div>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 tile_stats_count">
                                    <span class="count_top"><i class="fa fa-reply"></i> Sales Refunded</span>
                                    <div class="count red">{{ number_format($summary->sales_refund,3) }}</div>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 tile_stats_count">
                                    <span class="count_top"><i class="fa fa-exchange"></i> Return Exchange Sales</span>
                                    <div class="count red">{{ number_format($summary->retex,3) }}</div>
                                </div>
                                <div class="col-md-3 col-sm-12 col-xs-12 tile_stats_count">
                                    <span class="count_top"><i class="fa fa-dollar"></i> Revenue Sales</span>
                                    <div class="count green">{{ number_format($summary->revenue,3) }}</div>
                                </div>
                                
                              </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content table-responsive">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Company Name</th>
                                            <th>Branch Name</th>
                                            <th>Terminal #</th>
                                            <th>Transaction #</th>
                                            <th>Sales Man</th>
                                            <th>User</th>
                                            <th>Member</th>
                                            <th>Gross Amount</th>
                                            <th>Net Amount</th>
                                            <th>Sub Total Discount</th>
                                            <th>Total Item Discount</th>
                                            <th>Return Exchange Amount</th>
                                            <th>Cash Amount</th>
                                            <th>Card Amount</th>
                                            <th>Gift Amount</th>
                                            <th>Charge Amount</th>
                                            <th>Check Amount</th>
                                            <th>Account Amount</th>
                                            <th>ATM Amount</th>
                                            <th>Deffered Amount</th>
                                            <th>Other Payment</th>
                                            <th>Date Time</th>
                                            <th>Posting Time</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>


                                    <tbody>
                                        @if(count($items) > 0)
                                        @foreach($items as $item)
                                        <tr>
                                            <td>{{ $item->company_name }}</td>
                                            <td>{{ $item->branch_name }}</td>
                                            <td>{{ $item->terminal_no }}</td>
                                            <td>{{ $item->transaction_no }}</td>
                                            <td>{{ $item->sales_man }}</td>
                                            <td>{{ $item->user }}</td>
                                            <td>{{ $item->member }}</td>
                                            <td>{{ number_format($item->gross_amount,2) }}</td>
                                            <td>{{ number_format($item->net_amount,2) }}</td>
                                            <td>{{ number_format($item->sub_total_discount,2) }}</td>
                                            <td>{{ number_format($item->total_item_discount,2) }}</td>
                                            <td>{{ number_format($item->retex_amount,2) }}</td>
                                            <td>{{ number_format($item->cash_amount,2) }}</td>
                                            <td>{{ number_format($item->card_amount,2) }}</td>
                                            <td>{{ number_format($item->gift_amount,2) }}</td>
                                            <td>{{ number_format($item->charge_amount,2) }}</td>
                                            <td>{{ number_format($item->check_amount,2) }}</td>
                                            <td>{{ number_format($item->account_amount,2) }}</td>
                                            <td>{{ number_format($item->atm_amount,2) }}</td>
                                            <td>{{ number_format($item->deffered_amount,2) }}</td>
                                            <td>{{ number_format($item->other_payment,2) }}</td>
                                            <td>{{ $item->local_time }}</td>
                                            <td>{{ $item->created_at }}</td>
                                            <td><a href="{{ route('sales.show', $item->id)}}"> Details</a></td>
                                        </tr>
                                        @endforeach
                                        
                                        @endif
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            
          </div>
    </div>
    <!-- /page content -->

@endsection